module.exports = {
  GCLOUD_PROJECT: process.env.GCLOUD_PROJECT,
  DATA_BACKEND: process.env.DATA_BACKEND,
  MYSQL_USER: process.env.MYSQL_USER,
  MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,
  MYSQL_TABLE: process.env.MYSQL_TABLE,
  MYSQL_DATABASE: process.env.MYSQL_DATABASE,
  INSTANCE_CONNECTION_NAME: process.env.INSTANCE_CONNECTION_NAME
}